// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using SwaggerClient.Models;

namespace SwaggerClient.Models
{
    public static partial class CurrencyDataCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<CurrencyData> DeserializeJson(JToken inputObject)
        {
            IList<CurrencyData> deserializedObject = new List<CurrencyData>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                CurrencyData currencyData = new CurrencyData();
                currencyData.DeserializeJson(iListValue);
                deserializedObject.Add(currencyData);
            }
            return deserializedObject;
        }
    }
}
